### ISSUE TITLE
DEPRECATED: global use of must_equal from test/base_policy_inherited_actors_test.rb:119. Use _(obj).must_equal instead. This will fail in Minitest 6.

### ISSUE THREAD

**Issue by joshmfrankel** [lessonly/accessly#36]

**Comment by rreinhardt9** [comment]
I had to look this up to understand what was going on, here was a helpful SO post on it: https://stackoverflow.com/questions/58128241/minitest-warning-deprecated-global-use-of-must-match-use-obj
